[DEFAULT]
APP_NAME = VCC Git
RUN_MODE = prod

[server]
ROOT_URL = https://git.{{ domain_name }}
DOMAIN = git.{{ domain_name }}
HTTP_PORT = {{ forgejo_port }}

SSH_PORT = 2222
LFS_START_SERVER = true
LFS_JWT_SECRET = "{{ lookup('password', '/dev/null', length=64) }}"

OFFLINE_MODE = true

[indexer]
REPO_INDEXER_ENABLED = false # breaks with multiple instances

[cache]
ENABLED = true
ADAPTER = redis
HOST    = network=tcp,addr=redis:6379,db=2,pool_size=100,idle_timeout=180s
ITEM_TTL = 16h

[security]
INSTALL_LOCK = true
SECRET_KEY = "{{ lookup('password', '/dev/null', length=64) }}"
COOKIE_USERNAME = vcc_git_username
COOKIE_REMEMBER_NAME = vcc_git_remember_me
INTERNAL_TOKEN = "{{ lookup('password', '/dev/null', length=64) }}"

[database]
# TODO[VCC-011]: Configure Forgejo to use postgres
DB_TYPE = postgres
HOST = {{ db_host }}:{{ db_port }}
NAME = {{ db_name }}
USER = {{ db_user }}
PASSWD = {{ db_password }}

[service]
ALLOW_ONLY_EXTERNAL_REGISTRATION = true

[oauth2_client]
REGISTER_EMAIL_CONFIRM = false
ENABLE_AUTO_REGISTRATION = true
USERNAME = nickname
ACCOUNT_LINKING = login

[session]
PROVIDER = redis
PROVIDER_CONFIG = network=tcp,addr=redis:6379,db=1,pool_size=100,idle_timeout=180s
COOKIE_NAME = forgejo_session
COOKIE_SECURE = true
SAME_SITE = lax
SESSION_LIFE_TIME = 86400
DOMAIN = 
GC_INTERVAL_TIME = 86400

[queue]
TYPE = redis
CONN_STR = redis://redis:6379/3
QUEUE_LENGTH = 20
BATCH_LENGTH = 20
MAX_WORKERS = 10

# TODO[VCC-020]: Enable configuration to export metrics to Prometheus (Forgejo)
[metrics]
ENABLED = true