vrrp_instance VI_1 {
    state {{ 'MASTER' if inventory_hostname == groups['targets'][0] else 'BACKUP' }}
    interface {{ workload_INT }}
    virtual_router_id 255
    priority {{ '100' if inventory_hostname == groups['targets'][0] else '90' }}
    advert_int 1

    authentication {
        auth_type PASS
        auth_pass {{ keepalive_auth_pass }}
    }

    virtual_ipaddress {
        {{ keepalive_virtual_ip }}
    }
}