---
# configure docker to accept insecure registries
- name: Copy docker daemon.json
  ansible.builtin.template:
    src: daemon.json
    dest: /etc/docker/daemon.json
  notify: Restart docker
- meta: flush_handlers